{
 "title": "Crawlspace",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Front",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{id=\"crawlspace1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Back",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{id=\"crawlspace2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "temperature{id=\"crawlspace1\"}",
     "legendFormat": "Front"
    },
    {
     "expr": "temperature{id=\"crawlspace2\"}",
     "legendFormat": "Back"
    }
   ]
  },
  { "title": "Humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Front",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "humidity{id=\"crawlspace1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Back",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "humidity{id=\"crawlspace2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "humidity{id=\"crawlspace1\"}",
     "legendFormat": "Front"
    },
    {
     "expr": "humidity{id=\"crawlspace2\"}",
     "legendFormat": "Back"
    }
   ]
  }
 ]
}