{
 "title": "Wind",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Wind Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wind_avg{id=\"tempest\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "wind_avg{id=\"tempest\"}",
     "legendFormat": "Wind"
    }
   ]
  },
  {
   "title": "Wind Gusts",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wind_gust{id=\"tempest\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "wind_gust{id=\"tempest\"}",
     "legendFormat": "Gusts"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "Feels Like",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "feels_like{id=\"tempest\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery{id=\"tempest\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "battery{id=\"tempest\"}",
     "legendFormat": "Battery"
    }
   ]
  }
 ]
}