#!/bin/sh
#
#	houseIoT
#	Copyright (c) 2022 Johan A. Goossens. All rights reserved.
#
#	This work is licensed under the terms of the MIT license.
#	For a copy, see <https://opensource.org/licenses/MIT>.

#
#	Add tools
#

sudo apt install -y vim dialog

#
#	Install mDNS
#

sudo apt install -y avahi-daemon

#
#	Install packages to allow apt to use a repository over HTTPS
#

sudo apt install -y ca-certificates curl gnupg lsb-release

sudo mkdir -p /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

#
#	Setup docker repository
#

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

#
#	Install docker engine, containerd, and docker compose
#

sudo apt update
sudo apt install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

#
#	Add permissions
#

sudo usermod -aG docker ${LOGNAME}
