---
global:
  scrape_interval: 1m
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: 'Alertmanager'

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'speedtest'
    scrape_interval: 30m
    scrape_timeout: 60s
    static_configs:
      - targets: ['speedtest:9798']

  - job_name: 'ping'
    metrics_path: /probe
    scrape_interval: 30m
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
        - pinghosts.yaml
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*);(.*)'  #first is the url, thus unique for instance
        target_label: instance
        replacement: $1
      - source_labels: [__address__]
        regex: '(.*);(.*)'  #second is humanname to use in charts
        target_label: humanname
        replacement: $2
      - source_labels: [instance]
        target_label: __param_target
      - target_label: __address__
        replacement: ping:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'attic'
    static_configs:
      - targets: ['10.0.1.201']

  - job_name: 'crawlspace'
    static_configs:
      - targets: ['10.0.1.202', '10.0.1.203']

  - job_name: 'tempest'
    static_configs:
      - targets: ['172.17.0.1:9999']
